const express = require('express')
const route = express.Router()

const UserController = require('../controller/user_controller')
const NitnemController = require('../controller/nitnem_controller')
const HappinessController = require('../controller/happiness_controller')
const GoodBehaviourController = require('../controller/good_behaviour_controller')
const SewaController = require('../controller/sewa_controller')
const PlanetCareController = require('../controller/planet_care_controller')
route.post('/login', UserController.login)
route.post('/signUp', UserController.signUp)
route.post('/changePassword', UserController.changePassword)
route.post('/getOtp', UserController.getOtp)
route.post('/verifyOtp', UserController.verifyOtp)
route.post('/fetchNitnemTask', NitnemController.fetchTask)
route.post('/fetchSewaTask', SewaController.fetchTask)
route.post('/addNewSewaTask', SewaController.addNewTask)
route.post('/fetchHappinessTask', HappinessController.fetchTask)
route.post('/addNewHappinessTask', HappinessController.addNewTask)
route.post('/fetchGoodBehaviourTask', GoodBehaviourController.fetchTask)
route.post('/fetchPlanetCareTask', PlanetCareController.fetchTask)

module.exports = route;