const express = require('express')
const route = express.Router()

const UserController = require('../controller/user_controller')
const NitnemController = require('../controller/nitnem_controller')
const HappinessController = require('../controller/happiness_controller')
const GoodBehaviourController = require('../controller/good_behaviour_controller')
const SewaController = require('../controller/sewa_controller')
const PlanetCareController = require('../controller/planet_care_controller')
route.post('/login', UserController.login)
route.post('/signUp', UserController.signUp)
route.post('/change_password', UserController.changePassword)
route.post('/get_otp', UserController.getOtp)
route.post('/verify_otp', UserController.verifyOtp)
route.post('/fetch_nitnem_task', NitnemController.fetchTask)
route.post('/fetch_sewa_task', SewaController.fetchTask)
route.post('/add_new_sewa_task', SewaController.addNewTask)
route.post('/fetch_happiness_task', HappinessController.fetchTask)
route.post('/add_new_happiness_task', HappinessController.addNewTask)
route.post('/fetch_good_behaviour_task', GoodBehaviourController.fetchTask)
route.post('/add_good_behaviour_task',  GoodBehaviourController.addNewTask)
route.post('/fetch_planet_care_task', PlanetCareController.fetchTask)

module.exports = route;